name: docker-buildx

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  SUB_DIRECTORY: rtsp-stream
  DOCKER_NAMESPACE: lhysin
  DOCKER_REPONAME: rtsp-stream
  DOCKER_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clone repository
        run: git clone 'https://github.com/Roverr/rtsp-stream'

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.SUB_DIRECTORY }} # subdirectory
          file: ${{ env.SUB_DIRECTORY }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.DOCKER_NAMESPACE }}/${{ env.DOCKER_REPONAME }}:${{ env.DOCKER_TAG }}
