name: deploy-docker-alpine-python3

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  DOCKER_NAMESPACE: lhysin/test
  DOCKER_REPONAME: docker-alpine-python3
  DOCKER_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout workflow repository
        uses: actions/checkout@v6

      - name: Clone and build Docker image
        uses: ./.github/actions/clone-and-docker-build
        with:
          repository_url: https://github.com/Docker-Hub-frolvlad/docker-alpine-python3.git
          docker_context: ./docker-alpine-python3
          dockerfile: ./docker-alpine-python3/Dockerfile
          image_tag: |
            ${{ secrets.DOCKER_REGISTRY }}/${{ env.DOCKER_NAMESPACE }}/${{ env.DOCKER_REPONAME }}:${{ env.DOCKER_TAG }}
            ${{ secrets.DOCKER_REGISTRY }}/${{ env.DOCKER_NAMESPACE }}/${{ env.DOCKER_REPONAME }}:build-${{ github.run_number }}
          docker_registry: ${{ secrets.DOCKER_REGISTRY }}
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
