name: deploy-koin-front

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout koin repository
        uses: actions/checkout@v2
        with:
          repository: lhysin/koin
          ref: main
          token: ${{ secrets.LHYSIN_UN_EXPIARY_GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies in koin repo
        run: |
          npm install
          npm run generate

      - name: Prepare static files for deployment
        run: |
          mkdir -p deploy  # deploy 폴더 생성
          cp -R ./dist/* ./deploy/  # dist 폴더 내용을 deploy 폴더로 복사

      - name: Upload deployment artifacts
        uses: actions/upload-artifact@v3
        with:
          name: static-files
          path: deploy/

  deploy:
    runs-on: ubuntu-latest
    needs: build  # build job 완료 후 실행
    steps:
      - name: Download deployment artifacts
        uses: actions/download-artifact@v3
        with:
          name: static-files

      - name: Prepare static files for deployment
        run: |
          git checkout deploy-static-file || git checkout -b deploy-static-file
          rm -rf ./*
          cp -r static-files/* ./

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .
          git commit -m "[$(date +'%Y-%m-%d')] Deploy static files" || echo "No changes to commit"
          git push --force origin deploy-static-file
