name: deploy-koin-front

on:
  workflow_dispatch:

permissions:
  contents: write

env:
  SUB_DIRECTORY: koin
  SOURCE_REPO: https://github.com/lhysin/koin
  TARGET_BRANCH: deploy-static-file

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clone source repository
        run: git clone ${{ env.SOURCE_REPO }}

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: |
          cd ${{ env.SUB_DIRECTORY }}
          npm install

      - name: Build Nuxt.js static files
        run: |
          cd ${{ env.SUB_DIRECTORY }}
          npm run build
          npm run generate

      - name: Backup dist folder
        run: |
          mkdir -p ../dist-backup
          cp -r ${{ env.SUB_DIRECTORY }}/dist/* ../dist-backup/

      - name: Checkout target branch (deploy-static-file)
        run: |
          cd koin  # 기존 저장소로 이동
          git fetch --all  # 원격 저장소 정보 최신화
          git checkout ${{ env.TARGET_BRANCH }} || git checkout -b ${{ env.TARGET_BRANCH }}  # 원격 브랜치가 없으면 로컬 브랜치 생성

      - name: Clear old files in target branch
        run: |
          cd koin  # 대상 디렉토리로 이동
          rm -rf *

      - name: Restore dist folder
        run: |
          cd koin  # 대상 디렉토리로 이동
          cp -r ../dist-backup/* ./

      - name: Create .nojekyll file
        run: |
          cd koin  # 대상 디렉토리로 이동
          touch .nojekyll

      - name: Commit and push changes to deploy-static-file branch
        run: |
          cd koin  # 대상 디렉토리로 이동
          git config --global user.name "lhysin"
          git config --global user.email "lhysin.main@gmail.com"
          git add .
          git commit -m "Deploy static files"
          
          # GitHub Actions 인증을 위한 토큰 설정
          git remote set-url origin https://x-access-token:${{ secrets.LHYSIN_UN_EXPIARY_GITHUB_TOKEN }}@github.com/lhysin/koin.git
          
          # 브랜치 푸시
          git push origin ${{ env.TARGET_BRANCH }} || git push -u origin ${{ env.TARGET_BRANCH }}
