name: deploy-world-smallest-docker-image

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
  DOCKER_NAMESPACE: lhysin
  DOCKER_REPONAME: world-smallest-docker-image
  DOCKER_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout workflow repository
        uses: actions/checkout@v6

      - name: Clone and build Docker image
        uses: ./.github/actions/clone-and-docker-build
        with:
          repository_url: https://github.com/dooqod/world-smallest-docker-image.git
          docker_context: ./world-smallest-docker-image
          dockerfile: ./world-smallest-docker-image/Dockerfile
          docker_registry: ${{ env.DOCKER_REGISTRY }}
          docker_namespace: ${{ env.DOCKER_NAMESPACE }}
          docker_reponame: ${{ env.DOCKER_REPONAME }}
          docker_tag: ${{ env.DOCKER_TAG }}
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
