name: deploy-koin-front

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout koin repository
        uses: actions/checkout@v2
        with:
          repository: lhysin/koin
          ref: main

      - name: Set up Node.js
        uses: actions/setup-node@v3

      # 3. koin 레포지토리에서 npm install
      - name: Install dependencies in koin repo
        run: |
          cd koin
          npm install
          npm run build

      - name: Prepare static files for deployment
        run: |
          mkdir -p ./deploy  # deploy 폴더 생성
          cp -R .koin/dist/* ./deploy/  # dist 폴더의 내용을 deploy 폴더로 복사
          cd koin
          git checkout -b deploy-static-file || git checkout deploy-static-file

      - name: Commit and push changes
        run: |
          cd koin
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .
          git commit -m "Deploy static files" || echo "No changes to commit"
          git push --force origin deploy-static-file

