name: deploy-koin-front

on:
  workflow_dispatch:

permissions:
  contents: write

env:
  SUB_DIRECTORY: koin
  SOURCE_REPO: https://github.com/lhysin/koin
  TARGET_BRANCH: deploy-static-file

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. private-build-deploy 레포지토리에서 액션 실행
    - name: Checkout private-build-deploy repo
      uses: actions/checkout@v3

    # 2. koin 레포지토리의 main 브랜치 체크아웃
    - name: Checkout koin repo
      uses: actions/checkout@v3
      with:
        repository: lhysin/koin
        ref: main
        path: koin

    # 3. koin 레포지토리로 이동
    - name: Change to koin directory
      run: cd koin

    # 4. koin 레포지토리에서 npm install
    - name: Install dependencies
      run: |
        cd koin
        npm install

    # 5. nuxt 빌드
    - name: Build Nuxt app
      run: |
        cd koin
        npm run build

    # 6. dist 폴더 백업
    - name: Backup dist folder
      run: |
        mv koin/dist koin/dist-backup

    # 7. deploy-static-file 브랜치 체크아웃
    - name: Checkout deploy-static-file branch
      run: |
        cd koin
        git checkout deploy-static-file

    # 8. 백업한 dist 파일을 deploy-static-file 브랜치에 복사
    - name: Copy dist files to deploy-static-file branch
      run: |
        cp -r koin/dist-backup/* koin/

    # 9. 커밋하고 푸시
    - name: Commit and push changes
      run: |
        cd koin
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Deploy Nuxt static files"
        git push origin deploy-static-file
