name: deploy-koin-front

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  SUB_DIRECTORY: koin
  SOURCE_REPO: https://github.com/lhysin/koin
  TARGET_REPO: https://github.com/lhysin/deploy-koin.git
  TARGET_DIR: deploy-koin

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clone source repository
        run: git clone ${{ env.SOURCE_REPO }}

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: ${{ env.SUB_DIRECTORY }}

      - name: Build Nuxt.js static files
        run: |
          cd ${{ env.SUB_DIRECTORY }}
          npm run build
          npm run generate

      - name: Clone target repository
        run: git clone ${{ env.TARGET_REPO }}

      - name: Print directory structure of target repo
        run: |
          echo "Directory structure of ${{ env.TARGET_DIR }}:"
          tree ${{ env.TARGET_DIR }} -L 2  # Adjust L as needed

      - name: Delete all files in target repository
        run: |
          cd ${{ env.TARGET_DIR }}
          rm -rf *  # 모든 파일 삭제

      - name: Copy dist files to target repository
        run: |
          cp -r ${{ env.SUB_DIRECTORY }}/dist/* ${{ env.TARGET_DIR }}/

      - name: Create .nojekyll file
        run: |
          cd ${{ env.TARGET_DIR }}
          touch .nojekyll  # .nojekyll 파일 생성

      - name: Commit and push changes
        run: |
          cd ${{ env.TARGET_DIR }}
          git config --global user.name "lhysin"
          git config --global user.email "lhysin.main@gmail.com"
          git add .
          git commit -m "Deploy static files"
          
          # GitHub Actions 인증을 위한 토큰 설정
          git remote set-url origin https://x-access-token:${{ secrets.LHYSIN_UN_EXPIARY_GITHUB_TOKEN }}@github.com/lhysin/${{ env.TARGET_DIR }}.git
          
          git push origin master  # 'master' 브랜치 사용
