name: deploy-cowcare-api

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  SUB_DIRECTORY: Cowcare-api
  DOCKER_NAMESPACE: lhysin
  DOCKER_REPONAME: cowcare-api
  DOCKER_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clone repository
        run: git clone ${{ secrets.COWCARE_API_REPOSITORY_WITH_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew bootJar
        working-directory: ${{ env.SUB_DIRECTORY }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.SUB_DIRECTORY }} # subdirectory
          file: ${{ env.SUB_DIRECTORY }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.DOCKER_NAMESPACE }}/${{ env.DOCKER_REPONAME }}:${{ env.DOCKER_TAG }}

  deploy:
   needs: build
   runs-on: ubuntu-latest
   steps:
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker stop ${{ env.DOCKER_REPONAME }}
            docker image rm -f ${{ env.DOCKER_NAMESPACE }}/${{ env.DOCKER_REPONAME }}
            docker pull ${{ env.DOCKER_NAMESPACE }}/${{ env.DOCKER_REPONAME }}:${{ env.DOCKER_TAG }}
            docker run -d -p 7880:7880 --name ${{ env.DOCKER_REPONAME }} \
            -e SPRING_DATASOURCE_URL=${{ secrets.COWCARE_SPRING_DATASOURCE_URL }} \
            -e SPRING_DATASOURCE_USERNAME=${{ secrets.COWCARE_SPRING_DATASOURCE_USERNAME }} \
            -e SPRING_DATASOURCE_PASSWORD=${{ secrets.COWCARE_SPRING_DATASOURCE_PASSWORD }} \
            -e SPRING_PROFILES_ACTIVE=development \
            -e loki.push-server=${{ secrets.LOKI_PUSH_SERVER }} \
            ${{ env.DOCKER_NAMESPACE }}/${{ env.DOCKER_REPONAME }}:${{ env.DOCKER_TAG }}
            curl -X DELETE -u "${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }}" https://index.docker.io/v1/repositories/${{ env.DOCKER_NAMESPACE }}/${{ env.DOCKER_REPONAME }}
