name: test-build-deploy

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clone repository
        run: git clone ${{ secrets.BITBUCKET_TEST_REPOSITORY_WITH_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew bootJar
        working-directory: cws/item-apiserver

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: cws/item-apiserver # subdirectory
          file: cws/item-apiserver/Dockerfile
#          platforms: linux/amd64,linux/arm64
          platforms: linux/arm64
          push: false
          outputs: type=tar, dest=local-cws-item-apiserver.tar
          tags: lhysin/local-cws-item-apiserver:latest

#   deploy:
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
    
      - name: Copy Docker image to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: local-cws-item-apiserver.tar
          target: ~/images
    
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker load -i ~/images/local-cws-item-apiserver.tar
            docker stop local-cws-item-apiserver
            docker image rm -f lhysin/local-cws-item-apiserver
            docker rm -f local-cws-item-apiserver
            docker run -d -p 9880:8880 --name local-cws-item-apiserver lhysin/local-cws-item-apiserver:latest
            #rm -rf ~/images
