name: test-build-deploy

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clone repository
        run: git clone ${{ secrets.BITBUCKET_TEST_REPOSITORY_WITH_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew bootJar
        working-directory: cws/item-apiserver

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: cws/item-apiserver # subdirectory
          file: cws/item-apiserver/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: lhysin/local-cws-item-apiserver:latest

  deploy:
   needs: build
   runs-on: ubuntu-latest
   steps:
    
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker stop local-cws-item-apiserver
            docker image rm -f lhysin/local-cws-item-apiserver
            docker pull lhysin/local-cws-item-apiserver:latest
            docker run -d -p 0880:8880 --name local-cws-item-apiserver \
            -e loki.push-server=${{ secrets.LOKI_PUSH_SERVER }} \
            lhysin/local-cws-item-apiserver:latest
            curl -X DELETE -u "${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }}" https://index.docker.io/v1/repositories/lhysin/local-cws-item-apiserver
